apiVersion: v1
kind: Service
metadata:
  name: api-web
  namespace: development
spec:
  selector:
    app: api-web
  ports:
    - protocol: TCP
      appProtocol: kubernetes.io/h2c
      port: 3000
      targetPort: 3000
  type: LoadBalancer